services:
  - type: web
    name: NativeShadowBot
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: python main.py
    envVars:
      - key: TELEGRAM_TOKEN
        value: TO_BE_SET_IN_RENDER
      - key: ELEVENLABS_API_KEY
        value: TO_BE_SET_IN_RENDER
      - key: WEBHOOK_HOST
        value: https://your-app-name.onrender.com  # замени на свой домен